import React, { useMemo, useState } from 'react';
import { CalendarDays, FileText, Plus, X } from 'lucide-react';
import { DISCIPLINES, DOCUMENTS, STRATEGIES } from '../data/catalogs';
import { Badge, Field, PageHeader, PriorityBadge, SectionCard, StatusBadge, TimelineDot, inputClass } from '../components/ui';
import { ExternalCoordinationPanel, TransferPanel } from '../components/CaseSpecialPanels';

function AttentionModal({ caseItem, onClose, onSave }) {
  const [form,setForm]=useState({date:'2026-09-15',type:'Consejería',discipline:'Psicología',title:'Atención de seguimiento',detail:'',recommendations:'',nextAction:'',nextActionDate:''});
  return <div className="fixed inset-0 bg-stone-950/40 z-50 flex items-center justify-center p-4" onMouseDown={onClose}><div className="bg-white rounded-3xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="p-5 border-b flex justify-between"><div><p className="text-xs font-semibold text-teal-700 uppercase">Nueva atención</p><h3 className="text-lg font-bold">{caseItem.id}</h3></div><button onClick={onClose}><X size={18}/></button></div><div className="p-5 grid md:grid-cols-2 gap-4"><Field label="Fecha real de atención"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className={inputClass}/></Field><Field label="Estrategia / tipo"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value,title:e.target.value})} className={inputClass}>{STRATEGIES.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Disciplina"><select value={form.discipline} onChange={e=>setForm({...form,discipline:e.target.value})} className={inputClass}>{DISCIPLINES.map(d=><option key={d}>{d}</option>)}</select></Field><Field label="Próxima acción"><input value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})} className={inputClass} placeholder="Opcional"/></Field><div className="md:col-span-2"><Field label="Acciones realizadas"><textarea rows={4} value={form.detail} onChange={e=>setForm({...form,detail:e.target.value})} className={inputClass}/></Field></div><div className="md:col-span-2"><Field label="Recomendaciones"><textarea rows={3} value={form.recommendations} onChange={e=>setForm({...form,recommendations:e.target.value})} className={inputClass}/></Field></div></div><div className="p-5 border-t flex justify-end gap-2"><button onClick={onClose} className="border px-4 py-2 rounded-xl text-sm">Cancelar</button><button onClick={()=>{onSave({date:form.date,type:form.type,title:form.title,detail:`${form.detail}${form.recommendations?` Recomendaciones: ${form.recommendations}`:''}`,discipline:form.discipline});onClose();}} className="bg-teal-700 text-white px-4 py-2 rounded-xl text-sm font-semibold">Guardar atención</button></div></div></div>;
}

export default function CasesPage({state,actions,initialCaseId}){
  const [selectedId,setSelectedId]=useState(initialCaseId || state.cases[0]?.id);
  const [tab,setTab]=useState('summary');
  const [openAttention,setOpenAttention]=useState(false);
  const selected=state.cases.find(c=>c.id===selectedId)||state.cases[0];
  const person=state.people.find(p=>p.id===selected?.personId);
  const timeline=useMemo(()=>state.timeline.filter(t=>t.caseId===selected?.id).sort((a,b)=>b.date.localeCompare(a.date)),[state.timeline,selected?.id]);
  const [closeReason,setCloseReason]=useState('Propósitos de A.I. cumplidos y continuidad ordinaria recomendada.');

  if(!selected) return <div>No hay casos.</div>;
  return <div className="space-y-6"><PageHeader eyebrow="Gestión del caso" title="Casos de Atención Interdisciplinaria" description="El caso integra valoración, plan, instrumentos, atenciones, coordinaciones y cierre sin duplicar identidad." actions={<button onClick={()=>setOpenAttention(true)} className="bg-teal-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold flex items-center gap-2"><Plus size={16}/> Registrar atención</button>}/>
  <div className="grid xl:grid-cols-[340px_1fr] gap-5 items-start"><SectionCard title="Casos"><div className="space-y-2 max-h-[700px] overflow-y-auto">{state.cases.map(c=>{const p=state.people.find(x=>x.id===c.personId);return <button key={c.id} onClick={()=>{setSelectedId(c.id);setTab('summary')}} className={`w-full text-left border rounded-xl p-3 ${selected.id===c.id?'border-teal-300 bg-teal-50':'border-stone-200'}`}><div className="flex justify-between gap-2"><div><p className="text-sm font-semibold">{p?.name}</p><p className="text-xs font-mono text-stone-400 mt-0.5">{c.id}</p></div><PriorityBadge priority={c.priority}/></div><div className="mt-2"><StatusBadge status={c.status}/></div></button>})}</div></SectionCard>
  <div className="space-y-5"><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 bg-gradient-to-r from-stone-900 to-stone-800 text-white"><div className="flex justify-between gap-4 flex-wrap"><div><p className="text-xs text-stone-300">{selected.id}</p><h3 className="text-xl font-bold mt-1">{person?.name}</h3><p className="text-sm text-stone-300 mt-1">{person?.identification} · {person?.establishment}</p></div><div className="flex gap-2"><PriorityBadge priority={selected.priority}/><StatusBadge status={selected.status}/></div></div></div><div className="p-5 grid sm:grid-cols-2 lg:grid-cols-4 gap-4 text-sm"><div><p className="text-xs text-stone-400">Apertura</p><p className="font-semibold mt-1">{selected.openedAt}</p></div><div><p className="text-xs text-stone-400">Frecuencia</p><p className="font-semibold mt-1">{selected.frequency}</p></div><div><p className="text-xs text-stone-400">Disciplinas</p><p className="font-semibold mt-1">{selected.disciplines.join(', ')}</p></div><div><p className="text-xs text-stone-400">Modalidad(es)</p><p className="font-semibold mt-1">{person?.modalities.join(' + ')}</p></div></div></section>
  <div className="flex gap-1 border-b overflow-x-auto">{[['summary','Resumen'],['timeline','Línea de tiempo'],['plan','Plan de atención'],['documents','Instrumentos'],['external','Coordinaciones externas'],['transfer','Traslado'],['closure','Reporte / cierre']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-2.5 text-sm font-medium border-b-2 whitespace-nowrap ${tab===id?'border-teal-700 text-teal-800':'border-transparent text-stone-500'}`}>{label}</button>)}</div>
  {tab==='summary'&&<div className="grid lg:grid-cols-2 gap-5"><SectionCard title="Valoración vigente"><p className="text-sm text-stone-600">{selected.valuationSummary}</p><div className="mt-4"><p className="text-xs font-semibold text-stone-500 uppercase">Propósitos</p><ul className="mt-2 space-y-1 text-sm text-stone-700">{selected.purposes.map(p=><li key={p}>• {p}</li>)}</ul></div></SectionCard><SectionCard title="Próxima acción"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-teal-50 text-teal-700 rounded-xl flex items-center justify-center"><CalendarDays size={18}/></div><div><p className="text-sm font-semibold">{selected.nextAction||'Definir en seguimiento'}</p><p className="text-xs text-stone-500">{selected.nextActionDate||'Sin fecha asignada'}</p></div></div></SectionCard></div>}
  {tab==='timeline'&&<SectionCard title="Historial longitudinal" description="Atenciones individuales, intervenciones grupales, sesiones y eventos bajo el mismo caso."><div>{timeline.map((e,i)=><div key={e.id} className="flex gap-4 pb-5"><div className="flex flex-col items-center"><TimelineDot type={e.type}/>{i<timeline.length-1&&<div className="w-px flex-1 bg-stone-200 mt-1"/>}</div><div className="-mt-1"><div className="flex gap-2 items-center flex-wrap"><p className="font-semibold text-sm">{e.title}</p>{e.groupInterventionId&&<Badge tone="purple">Intervención grupal</Badge>}</div><p className="text-xs text-stone-500 mt-1">{e.date} · {e.discipline}</p><p className="text-sm text-stone-600 mt-2">{e.detail}</p></div></div>)}</div></SectionCard>}
  {tab==='plan'&&<SectionCard title="Plan de atención"><div className="space-y-4"><div><p className="text-xs font-semibold text-stone-500 uppercase mb-2">Estrategias</p><div className="flex gap-2 flex-wrap">{selected.strategies.map(s=><Badge key={s} tone="teal">{s}</Badge>)}</div></div><div><p className="text-xs font-semibold text-stone-500 uppercase mb-2">Disciplinas</p><div className="flex gap-2 flex-wrap">{selected.disciplines.map(d=><Badge key={d} tone="purple">{d}</Badge>)}</div></div><div><p className="text-xs font-semibold text-stone-500 uppercase">Frecuencia</p><p className="text-sm font-semibold mt-1">{selected.frequency}</p></div></div></SectionCard>}
  {tab==='documents'&&<SectionCard title="Hub documental" description="Los instrumentos se relacionan con el caso; no crean expedientes aislados."><div className="grid md:grid-cols-2 gap-3">{DOCUMENTS.map(d=><div key={d.id} className="border rounded-xl p-4 flex gap-3"><div className="w-9 h-9 bg-violet-50 text-violet-700 rounded-xl flex items-center justify-center"><FileText size={16}/></div><div><p className="text-sm font-semibold">{d.name}</p><p className="text-xs text-stone-500 mt-1">{d.code}</p><Badge tone={d.state.includes('Pendiente')?'amber':d.state.includes('Borrador')?'blue':'green'} className="mt-2">{d.state}</Badge></div></div>)}</div></SectionCard>}
  {tab==='external'&&<ExternalCoordinationPanel person={person}/>}
  {tab==='transfer'&&<TransferPanel caseItem={selected} person={person}/>}
  {tab==='closure'&&<SectionCard title="Reporte de A.I. / cierre" description="El reporte debe construirse desde el historial; no obligar a reescribir todo."><div className="space-y-4"><div className="grid md:grid-cols-3 gap-3">{[['Motivo / caso',selected.referenceId],['Atenciones registradas',timeline.length],['Estado',selected.status]].map(([l,v])=><div key={l} className="border rounded-xl p-3"><p className="text-xs text-stone-400">{l}</p><p className="text-sm font-semibold mt-1">{v}</p></div>)}</div><Field label="Resumen / motivo de cierre"><textarea rows={4} value={closeReason} onChange={e=>setCloseReason(e.target.value)} className={inputClass}/></Field>{selected.status!=='Cerrado'?<button onClick={()=>actions.closeCase(selected.id,{date:'2026-09-15',reason:closeReason})} className="bg-emerald-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold">Cerrar caso y generar reporte</button>:<Badge tone="green">Caso cerrado el {selected.closedAt}</Badge>}</div></SectionCard>}
  </div></div>{openAttention&&<AttentionModal caseItem={selected} onClose={()=>setOpenAttention(false)} onSave={(att)=>actions.addAttention(selected.id,att)}/>}</div>;
}
