import React,{useMemo,useState} from 'react';
import { Download, FileText, FolderOpen, Search, Upload } from 'lucide-react';
import PersonSearch from '../components/PersonSearch';
import { CASE_STATUSES, EXTERNAL_INSTITUTIONS, HELP_TEXT, PRIORITIES } from '../data/catalogs';
import { applyHierarchyFilters, canEditOperational, roleConfig, roleFilters, scopeItems } from '../utils/access';
import { downloadExcelLike } from '../utils/download';
import { AlertBanner, Badge, Field, HelpStrip, PageHeader, PriorityBadge, SectionCard, StatusBadge, Tabs, TimelineDot, inputClass } from '../components/ui';

const today='2026-09-16';

export default function CasesPage({state,actions,role,context}){
  const cfg=roleConfig(role); const editable=canEditOperational(role); const base=scopeItems(state.cases,role); const options=roleFilters(role,state.people);
  const [query,setQuery]=useState(''); const [filters,setFilters]=useState({region:'',localOffice:'',establishment:'',status:'',priority:''}); const [selectedId,setSelectedId]=useState(context?.caseId||null); const [tab,setTab]=useState('summary');
  const filtered=useMemo(()=>applyHierarchyFilters(base,filters).filter(c=>{const p=state.people.find(x=>x.id===c.personId);const q=query.trim().toLowerCase();if(filters.status&&c.status!==filters.status)return false;if(filters.priority&&c.priority!==filters.priority)return false;return !q||p?.name.toLowerCase().includes(q)||p?.identification.toLowerCase().includes(q)}),[base,filters,query,state.people]);
  const selected=base.find(c=>c.id===selectedId); const person=state.people.find(p=>p.id===selected?.personId);
  const exportRows=filtered.map(c=>{const p=state.people.find(x=>x.id===c.personId);return[p?.identification,p?.name,c.localOffice,c.establishment,c.status,c.priority,c.openedAt,c.closedAt||'']});
  const simpleEst=cfg.level==='establishment';
  const incomingTransfers=cfg.level==='local'?state.transfers.filter(t=>t.destinationOffice===cfg.scope&&t.status==='Pendiente de continuidad'):[];
  return <div className="space-y-6"><PageHeader eyebrow="Gestión del caso" title="Casos de Atención Interdisciplinaria" description={simpleEst?'El establecimiento consulta únicamente información mínima de las personas de su centro asociadas a A.I.':'Busque por identificación o nombre y use filtros para priorizar el trabajo o analizar el ámbito permitido.'} actions={!simpleEst&&<button onClick={()=>downloadExcelLike('casos_ai_filtrados',['Identificación','Nombre','Oficina Local','Establecimiento','Estado','Prioridad','Apertura','Cierre'],exportRows)} className="border px-3 py-2 rounded-xl text-sm font-semibold flex gap-2 items-center"><Download size={15}/> Exportar Excel</button>}/><HelpStrip>{HELP_TEXT.cases}</HelpStrip>
    {incomingTransfers.length>0&&<SectionCard title="Ingresos por traslado pendientes de continuidad" description="El caso llegó desde otra Oficina Local. Confirmar continuidad no equivale únicamente a recibir el expediente físico."><div className="space-y-2">{incomingTransfers.map(t=>{const p=state.people.find(x=>x.id===t.personId);return <div key={t.id} className="border border-violet-200 bg-violet-50/40 rounded-xl p-3 flex justify-between gap-3 items-center"><div><p className="text-sm font-semibold">{p?.name}</p><p className="text-xs text-stone-500">{t.sourceOffice} → {t.destinationOffice} · {t.destinationEstablishment}</p><p className="text-xs text-stone-500 mt-1">Estado: {t.status}</p></div><button onClick={()=>actions.continueTransfer(t.id)} className="bg-violet-700 text-white rounded-xl px-3 py-2 text-xs font-semibold">Confirmar continuidad</button></div>})}</div></SectionCard>}
    <SectionCard title="Buscar y filtrar" description={`${filtered.length} de ${base.length} caso(s) visibles.`}><div className="grid md:grid-cols-2 xl:grid-cols-6 gap-3"><div className="relative md:col-span-2"><Search size={15} className="absolute left-3 top-3 text-stone-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className={`${inputClass} pl-9`} placeholder="Identificación o nombre"/></div>{!simpleEst&&<><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className={inputClass}><option value="">Todos los estados</option>{CASE_STATUSES.map(x=><option key={x}>{x}</option>)}</select><select value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})} className={inputClass}><option value="">Todas las prioridades</option>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></>}{options.regions.length>0&&<select value={filters.region} onChange={e=>setFilters({...filters,region:e.target.value,localOffice:'',establishment:''})} className={inputClass}><option value="">Todas las regiones</option>{options.regions.map(x=><option key={x}>{x}</option>)}</select>}{options.localOffices.length>0&&<select value={filters.localOffice} onChange={e=>setFilters({...filters,localOffice:e.target.value,establishment:''})} className={inputClass}><option value="">Todas las OL</option>{options.localOffices.map(x=><option key={x}>{x}</option>)}</select>}{options.establishments.length>0&&<select value={filters.establishment} onChange={e=>setFilters({...filters,establishment:e.target.value})} className={inputClass}><option value="">Todos los establecimientos</option>{options.establishments.map(x=><option key={x}>{x}</option>)}</select>}</div></SectionCard>
    <div className={`grid ${simpleEst?'':'xl:grid-cols-[420px_1fr]'} gap-5 items-start`}><SectionCard title="Listado"><div className="space-y-2 max-h-[700px] overflow-y-auto">{filtered.map(c=>{const p=state.people.find(x=>x.id===c.personId);return <button key={c.id} onClick={()=>!simpleEst&&setSelectedId(c.id)} className={`w-full text-left border rounded-xl p-3 ${selectedId===c.id&&!simpleEst?'border-teal-300 bg-teal-50/50':''}`}><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold">{p?.name}</p><p className="text-xs text-stone-500">{p?.identification} · {c.establishment}</p><p className="text-xs text-stone-400 mt-1">Apertura {c.openedAt}{c.closedAt?` · Cierre ${c.closedAt}`:''}</p></div><div className="flex flex-col items-end gap-1"><StatusBadge status={c.status}/>{!simpleEst&&<PriorityBadge priority={c.priority}/>}</div></div></button>})}</div></SectionCard>
    {!simpleEst&&<div>{selected&&person?<CaseDetail state={state} actions={actions} role={role} caseItem={selected} person={person} tab={tab} setTab={setTab}/>:<SectionCard><p className="py-20 text-center text-sm text-stone-500">Seleccione un caso para consultar el detalle.</p></SectionCard>}</div>}</div>
  </div>;
}

function CaseDetail({state,actions,role,caseItem,person,tab,setTab}){
  const editable=canEditOperational(role); const cfg=roleConfig(role); const events=state.timeline.filter(t=>t.caseId===caseItem.id).sort((a,b)=>b.date.localeCompare(a.date)); const documents=state.documents.filter(d=>d.caseId===caseItem.id); const coords=state.coordinations.filter(c=>c.caseId===caseItem.id); const reports=state.reports.filter(r=>r.caseId===caseItem.id);
  const [docType,setDocType]=useState('Documento asociado'); const [docFile,setDocFile]=useState(null); const [coord,setCoord]=useState({institution:'CCSS',reason:'',responsible:'',status:'En seguimiento',notes:''}); const [transfer,setTransfer]=useState({destinationOffice:'Oficina Local Heredia',destinationEstablishment:'CEN San Pablo',region:'Región Central Norte',date:today,reason:'Cambio de zona de residencia.'}); const [report,setReport]=useState({type:'Reporte de situación atendida',reason:'Solicitud institucional',date:today,generatedBy:'Ana Morales'}); const [close,setClose]=useState({date:today,reason:'Propósitos de A.I. cumplidos'});
  const tabs=[{id:'summary',label:'Resumen'},{id:'timeline',label:'Línea de tiempo'},{id:'plan',label:'Plan de atención'}];
  if(editable) tabs.push({id:'documents',label:'Documentos'},{id:'coords',label:'Coordinaciones'},{id:'transfer',label:'Traslado'},{id:'reports',label:'Reportes'},{id:'closure',label:'Cierre'});
  return <div className="space-y-4"><SectionCard><div className="flex justify-between gap-4 flex-wrap"><div><p className="text-xl font-bold">{person.name}</p><p className="text-sm text-stone-500">{person.identification} · {caseItem.establishment}</p><p className="text-xs text-stone-400 mt-1">{caseItem.id} · Apertura {caseItem.openedAt}</p></div><div className="flex gap-2 items-start"><StatusBadge status={caseItem.status}/><PriorityBadge priority={caseItem.priority}/></div></div></SectionCard>
  {['regional','national'].includes(cfg.level)&&<AlertBanner tone="blue" title="Vista de consulta">El detalle individual mostrado en esta demo es de solo lectura. Los permisos definitivos sobre información sensible deben validarse institucionalmente.</AlertBanner>}
  <SectionCard><Tabs items={tabs} value={tab} onChange={setTab}/><div className="pt-5">
  {tab==='summary'&&<div className="grid md:grid-cols-2 gap-4"><div className="border rounded-xl p-4"><p className="text-xs text-stone-400">Valoración vigente</p><p className="text-sm mt-2">{caseItem.valuationSummary}</p></div><div className="border rounded-xl p-4"><p className="text-xs text-stone-400">Próxima acción</p><p className="text-sm font-semibold mt-2">{caseItem.nextAction||'Sin próxima acción registrada'}</p>{caseItem.nextActionDate&&<p className="text-xs text-stone-500">{caseItem.nextActionDate}</p>}</div><div className="md:col-span-2 border rounded-xl p-4"><p className="text-xs text-stone-400">Propósitos</p><ul className="text-sm mt-2 list-disc ml-5">{caseItem.purposes?.map(x=><li key={x}>{x}</li>)}</ul></div></div>}
  {tab==='timeline'&&<div>{events.map((e,i)=><div key={e.id} className="flex gap-3"><div className="flex flex-col items-center"><TimelineDot type={e.type}/>{i<events.length-1&&<span className="w-px bg-stone-200 flex-1 min-h-14"/>}</div><div className="pb-5"><p className="text-sm font-semibold">{e.title}</p><p className="text-xs text-stone-500">{e.date} · {e.discipline}{e.professional?` · ${e.professional}`:''}</p><p className="text-xs text-stone-600 mt-1">{e.detail}</p></div></div>)}</div>}
  {tab==='plan'&&<div className="grid md:grid-cols-3 gap-3"><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Estrategias</p><div className="flex flex-wrap gap-1 mt-2">{caseItem.strategies?.map(x=><Badge key={x} tone="teal">{x}</Badge>)}</div></div><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Disciplinas</p><div className="flex flex-wrap gap-1 mt-2">{caseItem.disciplines?.map(x=><Badge key={x} tone="purple">{x}</Badge>)}</div></div><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Frecuencia</p><p className="text-sm font-semibold mt-2">{caseItem.frequency}</p></div></div>}
  {tab==='documents'&&<div className="space-y-4"><div className="grid md:grid-cols-2 gap-2">{documents.map(d=><div key={d.id} className="border rounded-xl p-3 flex gap-3"><FolderOpen size={18} className="text-teal-700"/><div><p className="text-sm font-semibold">{d.name}</p><p className="text-xs text-stone-500">{d.type} · {d.date} · {d.uploadedBy}</p></div></div>)}</div><div className="border-t pt-4 grid md:grid-cols-3 gap-3"><Field label="Tipo"><input value={docType} onChange={e=>setDocType(e.target.value)} className={inputClass}/></Field><label className="block"><span className="text-xs font-semibold">Archivo</span><input type="file" onChange={e=>setDocFile(e.target.files?.[0])} className="mt-1.5 block w-full text-xs"/></label><button disabled={!docFile} onClick={()=>{actions.addDocument({caseId:caseItem.id,name:docFile.name,type:docType,date:today,uploadedBy:'Usuario demo'});setDocFile(null)}} className="self-end bg-teal-700 disabled:bg-stone-300 text-white rounded-xl py-2 text-sm font-semibold flex justify-center gap-2"><Upload size={15}/> Cargar</button></div></div>}
  {tab==='coords'&&<div className="space-y-4"><div className="space-y-2">{coords.map(c=><div key={c.id} className="border rounded-xl p-3"><div className="flex justify-between"><p className="text-sm font-semibold">{c.institution}</p><StatusBadge status={c.status}/></div><p className="text-xs text-stone-600 mt-2">{c.reason}</p><p className="text-xs text-stone-400 mt-1">Responsable: {c.responsible} · {c.date}</p></div>)}</div><div className="grid md:grid-cols-2 gap-3 border-t pt-4"><Field label="Institución"><select value={coord.institution} onChange={e=>setCoord({...coord,institution:e.target.value})} className={inputClass}>{EXTERNAL_INSTITUTIONS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Profesional responsable" hint="No se asume que sea el usuario digitador."><input value={coord.responsible} onChange={e=>setCoord({...coord,responsible:e.target.value})} className={inputClass}/></Field><Field label="Motivo"><textarea value={coord.reason} onChange={e=>setCoord({...coord,reason:e.target.value})} className={inputClass}/></Field><Field label="Estado"><input value={coord.status} onChange={e=>setCoord({...coord,status:e.target.value})} className={inputClass}/></Field></div><button onClick={()=>actions.addCoordination({...coord,caseId:caseItem.id,date:today})} className="bg-teal-700 text-white px-4 py-2 rounded-xl text-sm font-semibold">Registrar coordinación</button></div>}
  {tab==='transfer'&&<div className="space-y-4"><AlertBanner tone="blue" title="Traslado">Para la OL origen corresponde a un cierre por traslado. En destino se crea un ingreso pendiente de continuidad.</AlertBanner><div className="grid md:grid-cols-2 gap-3"><Field label="Oficina Local destino"><input value={transfer.destinationOffice} onChange={e=>setTransfer({...transfer,destinationOffice:e.target.value})} className={inputClass}/></Field><Field label="Establecimiento destino"><input value={transfer.destinationEstablishment} onChange={e=>setTransfer({...transfer,destinationEstablishment:e.target.value})} className={inputClass}/></Field><Field label="Región destino"><input value={transfer.region} onChange={e=>setTransfer({...transfer,region:e.target.value})} className={inputClass}/></Field><Field label="Fecha"><input type="date" value={transfer.date} onChange={e=>setTransfer({...transfer,date:e.target.value})} className={inputClass}/></Field><div className="md:col-span-2"><Field label="Motivo"><input value={transfer.reason} onChange={e=>setTransfer({...transfer,reason:e.target.value})} className={inputClass}/></Field></div></div><button disabled={caseItem.status==='Cerrado'} onClick={()=>actions.transferCase(caseItem.id,transfer)} className="bg-violet-700 disabled:bg-stone-300 text-white px-4 py-2 rounded-xl text-sm font-semibold">Cerrar por traslado</button></div>}
  {tab==='reports'&&<div className="space-y-4"><AlertBanner tone="blue" title="Reporte independiente del cierre">Puede generarse un reporte mientras el caso continúa activo.</AlertBanner><div className="space-y-2">{reports.map(r=><div key={r.id} className="border rounded-xl p-3 flex gap-3"><FileText size={18} className="text-violet-700"/><div><p className="text-sm font-semibold">{r.type}</p><p className="text-xs text-stone-500">{r.date} · {r.generatedBy}</p><p className="text-xs mt-1">{r.reason}</p></div></div>)}</div><div className="grid md:grid-cols-2 gap-3 border-t pt-4"><Field label="Tipo de reporte"><input value={report.type} onChange={e=>setReport({...report,type:e.target.value})} className={inputClass}/></Field><Field label="Motivo"><input value={report.reason} onChange={e=>setReport({...report,reason:e.target.value})} className={inputClass}/></Field></div><button onClick={()=>actions.addReport({...report,caseId:caseItem.id})} className="bg-teal-700 text-white px-4 py-2 rounded-xl text-sm font-semibold">Generar reporte</button></div>}
  {tab==='closure'&&<div className="space-y-4"><AlertBanner tone="amber" title="Cierre del caso">Cerrar el caso no equivale a egreso de CEN-CINAI ni impide otros seguimientos que continúen.</AlertBanner><div className="grid md:grid-cols-2 gap-3"><Field label="Fecha"><input type="date" value={close.date} onChange={e=>setClose({...close,date:e.target.value})} className={inputClass}/></Field><Field label="Motivo"><input value={close.reason} onChange={e=>setClose({...close,reason:e.target.value})} className={inputClass}/></Field></div><button disabled={caseItem.status==='Cerrado'} onClick={()=>actions.closeCase(caseItem.id,close)} className="bg-stone-900 disabled:bg-stone-300 text-white px-4 py-2 rounded-xl text-sm font-semibold">Cerrar caso</button></div>}
  </div></SectionCard></div>;
}
