import React from 'react';
import { AlertTriangle, ArrowRight, BookOpenCheck, CalendarDays, ClipboardList, FolderHeart, Users } from 'lucide-react';
import { HELP_TEXT } from '../data/catalogs';
import { roleConfig, scopeItems } from '../utils/access';
import { HelpStrip, MetricCard, PageHeader, SectionCard, StatusBadge } from '../components/ui';

export default function DashboardPage({state,role,onNavigate,actions}){
  const cfg=roleConfig(role);
  const people=scopeItems(state.people,role);
  const refs=scopeItems(state.references,role);
  const cases=scopeItems(state.cases,role);
  const schedule=scopeItems(state.schedule,role);
  const transfers=state.transfers.filter(t=>cfg.level==='local'&&t.destinationOffice===cfg.scope&&t.status==='Pendiente de continuidad');
  const overdue=schedule.filter(s=>s.status==='Programada'&&s.date<'2026-09-16');

  if(cfg.level==='establishment') return <div className="space-y-6"><PageHeader eyebrow="Establecimiento" title="Inicio" description="Acceso simplificado para referencia y consulta básica de personas asociadas a A.I."/><HelpStrip>{HELP_TEXT.dashboard}</HelpStrip>
    <div className="grid sm:grid-cols-3 gap-3"><MetricCard label="Referencias" value={refs.length} helper="De este establecimiento" icon={ClipboardList} tone="blue" onClick={()=>onNavigate('references')}/><MetricCard label="Personas en A.I." value={people.filter(p=>cases.some(c=>c.personId===p.id)).length} helper="Lista informativa" icon={Users} tone="teal" onClick={()=>onNavigate('cases')}/><MetricCard label="Pendientes de captura" value={state.syncItems.filter(x=>x.status!=='Sincronizado').length} helper="Laboratorio / contingencia" icon={AlertTriangle} tone="amber" onClick={()=>onNavigate('lab')}/></div>
    <SectionCard title="Acciones rápidas" description="El establecimiento no accede al detalle interno de los casos de A.I."><div className="flex gap-2 flex-wrap"><button onClick={()=>onNavigate('references',{newReference:true})} className="bg-teal-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold">Nueva referencia</button><button onClick={()=>onNavigate('cases')} className="border px-4 py-2.5 rounded-xl text-sm font-semibold">Ver lista de A.I.</button></div></SectionCard></div>;

  if(['regional','national'].includes(cfg.level)) return <div className="space-y-6"><PageHeader eyebrow={cfg.level==='regional'?'Nivel Regional':'Nivel Nacional'} title="Inicio" description="Vista de consulta y analítica. La operación del caso permanece en Oficina Local."/><HelpStrip>{HELP_TEXT.dashboard}</HelpStrip>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><MetricCard label="Personas visibles" value={people.length} icon={Users} tone="blue"/><MetricCard label="Casos activos" value={cases.filter(c=>c.status==='Activo').length} icon={FolderHeart} tone="teal"/><MetricCard label="Atenciones registradas" value={state.timeline.filter(t=>cases.some(c=>c.id===t.caseId)&&!['Sesión interdisciplinaria','Cierre','Traslado'].includes(t.type)).length} icon={Users} tone="purple"/><MetricCard label="Actividades programadas" value={schedule.filter(s=>s.status==='Programada').length} icon={CalendarDays} tone="amber" onClick={()=>onNavigate('schedule')}/></div>
    <div className="grid lg:grid-cols-2 gap-5"><SectionCard title="Consulta analítica"><p className="text-sm text-stone-600">Use Reporterías para seleccionar año, ámbito institucional, estado, prioridad, disciplina y profesional.</p><button onClick={()=>onNavigate('reporting')} className="mt-4 text-sm font-semibold text-teal-700 flex items-center gap-1">Abrir reportería <ArrowRight size={14}/></button></SectionCard><SectionCard title="Programación"><p className="text-sm text-stone-600">Puede consultar la programación de las Oficinas Locales de su ámbito, sin modificarla.</p><button onClick={()=>onNavigate('schedule')} className="mt-4 text-sm font-semibold text-teal-700">Consultar programación</button></SectionCard></div></div>;

  const pendingRefs=refs.filter(r=>['Pendiente de revisión','Recibida'].includes(r.status));
  const active=cases.filter(c=>c.status==='Activo');
  const nextSessions=state.sessions.filter(s=>s.status==='Programada');
  return <div className="space-y-6"><PageHeader eyebrow="Oficina Local" title="Buenos días. ¿Qué requiere atención hoy?" description="Panel operativo del equipo de Atención Interdisciplinaria." actions={<button onClick={()=>onNavigate('references')} className="bg-teal-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold flex items-center gap-2"><ClipboardList size={16}/> Referencias</button>}/><HelpStrip>{HELP_TEXT.dashboard}</HelpStrip>
    <div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-3"><MetricCard label="Referencias nuevas" value={pendingRefs.length} icon={ClipboardList} tone="amber" onClick={()=>onNavigate('references')}/><MetricCard label="Casos activos" value={active.length} icon={FolderHeart} tone="teal" onClick={()=>onNavigate('cases')}/><MetricCard label="Sesiones próximas" value={nextSessions.length} icon={BookOpenCheck} tone="purple" onClick={()=>onNavigate('sessions')}/><MetricCard label="Ingresos por traslado" value={transfers.length} icon={ArrowRight} tone="blue" onClick={()=>onNavigate('cases',{transferPending:true})}/><MetricCard label="Programación vencida" value={overdue.length} icon={CalendarDays} tone="red" onClick={()=>onNavigate('schedule')}/></div>
    {overdue.length>0&&<SectionCard title="Notificaciones"><div className="space-y-2">{overdue.map(x=><button key={x.id} onClick={()=>onNavigate('schedule')} className="w-full text-left border border-amber-200 bg-amber-50 rounded-xl p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold">{x.title}</p><p className="text-xs text-stone-600">Programada para {x.date}. Actualice si fue realizada, reprogramada o cancelada.</p></div><StatusBadge status={x.status}/></div></button>)}</div></SectionCard>}
    <div className="grid lg:grid-cols-2 gap-5"><SectionCard title="Referencias por revisar" description="Las referencias creadas desde establecimientos llegan a esta bandeja."><div className="space-y-2">{pendingRefs.slice(0,4).map(r=>{const p=state.people.find(x=>x.id===r.personId);return <button key={r.id} onClick={()=>onNavigate('references',{referenceId:r.id})} className="w-full border rounded-xl p-3 text-left hover:border-teal-300"><div className="flex justify-between"><div><p className="text-sm font-semibold">{p?.name}</p><p className="text-xs text-stone-500">{r.establishment} · {r.referredBy}</p></div><StatusBadge status={r.type}/></div></button>})}</div></SectionCard><SectionCard title="Próximas acciones"><div className="space-y-2">{active.filter(c=>c.nextAction).map(c=>{const p=state.people.find(x=>x.id===c.personId);return <button key={c.id} onClick={()=>onNavigate('cases',{caseId:c.id})} className="w-full text-left border rounded-xl p-3"><p className="text-sm font-semibold">{p?.name}</p><p className="text-xs text-stone-500">{c.nextAction} · {c.nextActionDate}</p></button>})}</div></SectionCard></div>
  </div>;
}
