import React, { useState } from 'react';
import { CheckCircle2, CloudUpload, FileScan, RefreshCcw, Wifi, WifiOff } from 'lucide-react';
import { AlertBanner, Badge, Field, PageHeader, SectionCard, StatusBadge, inputClass } from '../components/ui';

export default function LabPage({ state, actions }) {
  const [ocrStarted,setOcrStarted]=useState(true);
  const pending=state.syncItems.filter(s=>s.status!=='Sincronizado').length;
  return <div className="space-y-6"><PageHeader eyebrow="Exploración / prototipo" title="Laboratorio de demo" description="Funcionalidades importantes para validar concepto y UX. La infraestructura real se definirá en etapas posteriores."/>
    <div className="grid xl:grid-cols-2 gap-5"><SectionCard title="Modo offline y sincronización" description="Captura sin conexión + sincronización posterior, sin duplicar registros."><div className="space-y-4"><div className="flex items-center justify-between border rounded-xl p-4"><div className="flex gap-3 items-center"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${state.connection==='online'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{state.connection==='online'?<Wifi size={18}/>:<WifiOff size={18}/>}</div><div><p className="text-sm font-semibold">{state.connection==='online'?'Conectado':'Sin conexión'}</p><p className="text-xs text-stone-500">{pending} elemento(s) requieren atención</p></div></div><button onClick={()=>actions.setConnection(state.connection==='online'?'offline':'online')} className="border rounded-xl px-3 py-2 text-xs font-semibold">Cambiar estado</button></div><div className="space-y-2">{state.syncItems.map(item=><div key={item.id} className="border rounded-xl p-3 flex items-center justify-between gap-3"><div><p className="text-sm font-medium">{item.label}</p><p className="text-xs text-stone-400">{item.entity} · {item.lastModified}</p></div><StatusBadge status={item.status}/></div>)}</div><button onClick={actions.syncAll} className="w-full bg-teal-700 text-white rounded-xl py-2.5 text-sm font-semibold flex items-center justify-center gap-2"><RefreshCcw size={15}/> Simular recuperación y sincronizar</button></div></SectionCard>
    <SectionCard title="OCR con IA — captura asistida" description="Extraer → precargar → revisar → confirmar. La IA nunca guarda el dato definitivo por sí sola."><div className="space-y-4"><div className="border-2 border-dashed rounded-2xl p-5 bg-stone-50 text-center"><FileScan size={28} className="mx-auto text-stone-400"/><p className="text-sm font-semibold mt-2">Entrevista Familiar — demo</p><p className="text-xs text-stone-500 mt-1">Documento sintético / no contiene datos reales.</p><button onClick={()=>setOcrStarted(true)} className="mt-3 border border-stone-200 bg-white rounded-xl px-3 py-2 text-xs font-semibold inline-flex items-center gap-2"><CloudUpload size={14}/> Procesar documento</button></div>{ocrStarted&&<><AlertBanner tone="blue" title="Información extraída — requiere revisión">Los valores de baja confianza se destacan para revisión prioritaria.</AlertBanner><div className="space-y-3">{state.ocr.fields.map(field=><div key={field.id} className={`border rounded-xl p-3 ${field.confirmed?'border-emerald-200 bg-emerald-50/40':field.confidence<0.85?'border-amber-200 bg-amber-50/40':'border-stone-200'}`}><div className="flex items-center justify-between gap-3 mb-2"><p className="text-xs font-semibold text-stone-600">{field.label}</p><div className="flex gap-2"><Badge tone={field.confidence<0.85?'amber':'green'}>{Math.round(field.confidence*100)}% confianza</Badge>{field.confirmed&&<Badge tone="green"><CheckCircle2 size={11}/> Confirmado</Badge>}</div></div><div className="flex gap-2"><input value={field.value} onChange={e=>actions.updateOcrField(field.id,{value:e.target.value,confirmed:false})} className={inputClass}/><button onClick={()=>actions.updateOcrField(field.id,{confirmed:!field.confirmed})} className={`px-3 rounded-xl text-xs font-semibold border ${field.confirmed?'border-emerald-300 text-emerald-700':'border-stone-200'}`}>{field.confirmed?'Confirmado':'Confirmar'}</button></div></div>)}</div><button disabled={!state.ocr.fields.every(f=>f.confirmed)} className="w-full bg-teal-700 disabled:bg-stone-300 text-white rounded-xl py-2.5 text-sm font-semibold">Confirmar precarga en formulario</button></>}</div></SectionCard></div>
    <SectionCard title="Notas para arquitectura posterior"><div className="grid md:grid-cols-3 gap-3">{[['Offline','Definir almacenamiento local seguro, autenticación y conflictos.'],['OCR','Definir proveedor/infraestructura, privacidad y precisión mínima.'],['Integraciones','Confirmar APIs/servicios reales de SIDINACC antes de comprometer implementación.']].map(([t,d])=><div key={t} className="border rounded-xl p-4"><p className="text-sm font-bold">{t}</p><p className="text-xs text-stone-500 mt-2">{d}</p><Badge tone="amber" className="mt-3">NEEDS_VALIDATION</Badge></div>)}</div></SectionCard>
  </div>;
}
