import React,{useState} from 'react';
import { CheckCircle2, CloudUpload, Download, FileScan, FileSpreadsheet, RefreshCcw, Wifi, WifiOff } from 'lucide-react';
import { HELP_TEXT } from '../data/catalogs';
import { downloadReferenceTemplate } from '../utils/download';
import { AlertBanner, Badge, HelpStrip, PageHeader, SectionCard, StatusBadge, inputClass } from '../components/ui';

export default function LabPage({state,actions}){const [ocrStarted,setOcrStarted]=useState(true);const pending=state.syncItems.filter(s=>s.status!=='Sincronizado').length;return <div className="space-y-6"><PageHeader eyebrow="Exploración" title="Laboratorio" description="Funciones útiles para explorar, pero no comprometidas como núcleo de la primera implementación."/><HelpStrip>{HELP_TEXT.lab}</HelpStrip>
  <SectionCard title="Contingencia prioritaria — Excel estandarizado" description="La alternativa más simple para establecimientos sin conectividad suficiente."><div className="grid md:grid-cols-[1fr_auto] gap-4 items-center"><div><p className="text-sm text-stone-700">La persona completa una plantilla fuera de línea, luego la carga al sistema para precargar y revisar la referencia.</p><div className="mt-3 flex items-center gap-2"><Badge tone="green"><FileSpreadsheet size={12}/> Prioridad de diseño</Badge><Badge tone="blue">Revisión humana</Badge></div></div><button onClick={downloadReferenceTemplate} className="border rounded-xl px-4 py-2.5 text-sm font-semibold flex gap-2 items-center"><Download size={15}/> Descargar plantilla</button></div></SectionCard>
  <div className="grid xl:grid-cols-2 gap-5"><SectionCard title="Offline y sincronización — experimental" description="Explora continuidad ante fallas de conexión. Su arquitectura definitiva no está comprometida."><div className="space-y-4"><div className="flex justify-between border rounded-xl p-4"><div className="flex gap-3"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${state.connection==='online'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{state.connection==='online'?<Wifi size={18}/>:<WifiOff size={18}/>}</div><div><p className="text-sm font-semibold">{state.connection==='online'?'En línea':'Sin conexión'}</p><p className="text-xs text-stone-500">{pending} elemento(s) pendientes</p></div></div><button onClick={()=>actions.setConnection(state.connection==='online'?'offline':'online')} className="border rounded-xl px-3 text-xs font-semibold">Cambiar</button></div>{state.syncItems.map(x=><div key={x.id} className="border rounded-xl p-3 flex justify-between"><div><p className="text-sm font-semibold">{x.label}</p><p className="text-xs text-stone-500">{x.lastModified}</p></div><StatusBadge status={x.status}/></div>)}<button onClick={actions.syncAll} className="w-full bg-teal-700 text-white rounded-xl py-2.5 text-sm font-semibold flex justify-center gap-2"><RefreshCcw size={15}/> Simular sincronización</button></div></SectionCard>
  <SectionCard title="OCR con IA — experimental" description="Extraer → precargar → revisar → confirmar. Nunca guarda automáticamente un dato definitivo."><div className="space-y-4"><div className="border-2 border-dashed rounded-2xl p-5 bg-stone-50 text-center"><FileScan size={28} className="mx-auto text-stone-400"/><p className="font-semibold mt-2">Referencia A.I. física — demo</p><p className="text-xs text-stone-500">También podría explorarse para listas de asistencia grupales.</p><button onClick={()=>setOcrStarted(true)} className="mt-3 border bg-white rounded-xl px-3 py-2 text-xs font-semibold inline-flex gap-2"><CloudUpload size={14}/> Procesar documento</button></div>{ocrStarted&&<><AlertBanner tone="blue" title="Revisión obligatoria">Los valores con menor confianza requieren especial atención.</AlertBanner>{state.ocr.fields.map(f=><div key={f.id} className={`border rounded-xl p-3 ${f.confirmed?'border-emerald-200 bg-emerald-50/40':f.confidence<.85?'border-amber-200 bg-amber-50/40':''}`}><div className="flex justify-between gap-2 mb-2"><p className="text-xs font-semibold">{f.label}</p><div className="flex gap-2"><Badge tone={f.confidence<.85?'amber':'green'}>{Math.round(f.confidence*100)}%</Badge>{f.confirmed&&<Badge tone="green"><CheckCircle2 size={11}/> Confirmado</Badge>}</div></div><div className="flex gap-2"><input value={f.value} onChange={e=>actions.updateOcrField(f.id,{value:e.target.value,confirmed:false})} className={inputClass}/><button onClick={()=>actions.updateOcrField(f.id,{confirmed:!f.confirmed})} className="border rounded-xl px-3 text-xs font-semibold">{f.confirmed?'Confirmado':'Confirmar'}</button></div></div>)}</>}</div></SectionCard></div>
  </div>}
