import React, { useState } from 'react';
import { CheckCircle2, RotateCcw, ShieldCheck } from 'lucide-react';
import { AlertBanner, Badge, Field, PageHeader, SectionCard, StatusBadge, inputClass } from '../components/ui';

export default function QualityPage({ state, actions }) {
  const [selectedId,setSelectedId]=useState(state.qualitySubmissions[0]?.id);
  const [note,setNote]=useState('');
  const selected=state.qualitySubmissions.find(q=>q.id===selectedId)||state.qualitySubmissions[0];
  return <div className="space-y-6"><PageHeader eyebrow="ATE / Dirección Regional" title="Control de calidad" description="Revisión regional de completitud y consistencia antes de incorporar datos al Consolidado Regional."/>
    <div className="grid xl:grid-cols-[1fr_420px] gap-5 items-start"><SectionCard title="Remisiones de Oficinas Locales"><div className="space-y-2">{state.qualitySubmissions.map(q=><button key={q.id} onClick={()=>setSelectedId(q.id)} className={`w-full text-left border rounded-xl p-4 ${selected?.id===q.id?'border-violet-300 bg-violet-50':'border-stone-200'}`}><div className="flex justify-between gap-3 flex-wrap"><div><p className="text-sm font-bold">{q.office}</p><p className="text-xs text-stone-500 mt-1">{q.period} · {q.records} registros</p></div><StatusBadge status={q.status}/></div><div className="mt-3 flex gap-2"><Badge tone={q.issues?'red':'green'}>{q.issues} inconsistencia(s)</Badge></div></button>)}</div></SectionCard>
    {selected&&<SectionCard title="Revisión regional" description="La devolución conserva trazabilidad y permite corrección/reenvío."><div className="space-y-4"><div className="grid grid-cols-2 gap-3"><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Registros</p><p className="text-xl font-bold mt-1">{selected.records}</p></div><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Inconsistencias</p><p className="text-xl font-bold mt-1">{selected.issues}</p></div></div>{selected.notes.length>0?<AlertBanner tone="amber" title="Hallazgos de calidad"><ul className="list-disc ml-4 space-y-1">{selected.notes.map((n,i)=><li key={i}>{n}</li>)}</ul></AlertBanner>:<AlertBanner tone="green" title="Sin inconsistencias registradas">La remisión puede incorporarse al Consolidado Regional.</AlertBanner>}<Field label="Observación de revisión"><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} className={inputClass} placeholder="Motivo de devolución o nota de validación..."/></Field><div className="grid sm:grid-cols-2 gap-2"><button onClick={()=>{actions.updateQuality(selected.id,'Devuelto',note||'Devuelto para corrección.');setNote('')}} className="border border-red-200 text-red-700 hover:bg-red-50 px-3 py-2.5 rounded-xl text-sm font-semibold flex items-center justify-center gap-2"><RotateCcw size={15}/> Devolver a OL</button><button onClick={()=>{actions.updateQuality(selected.id,'Validado',note);setNote('')}} className="bg-emerald-700 text-white px-3 py-2.5 rounded-xl text-sm font-semibold flex items-center justify-center gap-2"><CheckCircle2 size={15}/> Validar</button></div><div className="pt-4 border-t text-xs text-stone-500 flex items-center gap-2"><ShieldCheck size={14}/> Toda corrección debe conservar quién, cuándo y qué cambió.</div></div></SectionCard>}</div>
  </div>;
}
