import React,{useMemo,useState} from 'react';
import { Download, FileSpreadsheet, Plus, Printer, Upload } from 'lucide-react';
import PersonSearch from '../components/PersonSearch';
import { DETECTION_ORIGINS, HELP_TEXT, REFERENCE_MOTIVES, REFERENCE_TYPES } from '../data/catalogs';
import { canCreateReference, roleConfig, scopeItems } from '../utils/access';
import { downloadReferenceTemplate, printReference } from '../utils/download';
import { AlertBanner, Badge, Field, HelpStrip, PageHeader, ProgressSteps, SectionCard, StatusBadge, inputClass } from '../components/ui';

const steps=['Persona y trazabilidad','Motivo','Información relevante','Revisar'];

function emptyForm(role){return {personId:null,date:'2026-09-16',type:'No inmediata',origin:'Observación directa',motives:[],factorDetails:{},observations:'',referredBy:role==='ESTABLISHMENT'?'María López — Asistente 3':'Ana Morales — Profesional EE.II.'};}

export default function ReferencesPage({state,actions,role,context}){
  const cfg=roleConfig(role); const visible=scopeItems(state.references,role); const [selectedId,setSelectedId]=useState(context?.referenceId||visible[0]?.id); const [creating,setCreating]=useState(Boolean(context?.newReference)); const [mode,setMode]=useState('manual'); const [step,setStep]=useState(0); const [form,setForm]=useState(emptyForm(role)); const [fileName,setFileName]=useState('');
  const selected=state.references.find(r=>r.id===selectedId); const person=state.people.find(p=>p.id===selected?.personId);
  const reset=()=>{setForm(emptyForm(role));setStep(0);setMode('manual');setFileName('');setCreating(false)};
  const toggleMotive=(m)=>setForm(f=>{const exists=f.motives.includes(m);const motives=exists?f.motives.filter(x=>x!==m):[...f.motives,m];const details={...f.factorDetails};if(exists)delete details[m];return{...f,motives,factorDetails:details}});
  const selectedPerson=state.people.find(p=>p.id===form.personId);
  const submit=()=>{if(!selectedPerson)return;actions.addReference({...form,status:'Pendiente de revisión',establishment:selectedPerson.establishment,localOffice:selectedPerson.localOffice,region:selectedPerson.region,categories:Object.entries(REFERENCE_MOTIVES).filter(([,arr])=>arr.some(x=>form.motives.includes(x))).map(([k])=>k)});reset()};
  const simulateExcel=(file)=>{setFileName(file?.name||'referencia_demo.xlsx');setMode('excel');setForm({...emptyForm(role),personId:'PER-001',origin:'Observación directa',motives:['Alteraciones emocionales'],factorDetails:{'Alteraciones emocionales':'Dato precargado desde plantilla de demostración.'},observations:'Información precargada para revisión desde una plantilla Excel estandarizada.',referredBy:'María López — Asistente 3'});setStep(3)};

  return <div className="space-y-6"><PageHeader eyebrow="Detección y referencia" title="Referencias a Atención Interdisciplinaria" description="La referencia conserva trazabilidad y reutiliza datos existentes. Cuando sea necesario, cada factor seleccionado puede especificarse con mayor detalle." actions={canCreateReference(role)&&<button onClick={()=>setCreating(true)} className="bg-teal-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold flex items-center gap-2"><Plus size={16}/> Nueva referencia</button>}/><HelpStrip>{HELP_TEXT.references}</HelpStrip>
    {creating&&<SectionCard title="Nueva referencia" description="Seleccione cómo desea iniciar la captura."><div className="space-y-5">
      <div className="flex gap-2"><button onClick={()=>setMode('manual')} className={`px-3 py-2 rounded-xl text-sm font-semibold border ${mode==='manual'?'bg-teal-50 border-teal-300 text-teal-800':''}`}>Digitar en el sistema</button><button onClick={()=>setMode('excel')} className={`px-3 py-2 rounded-xl text-sm font-semibold border ${mode==='excel'?'bg-teal-50 border-teal-300 text-teal-800':''}`}>Cargar Excel estandarizado</button></div>
      {mode==='excel'&&step===0?<div className="grid md:grid-cols-2 gap-4"><div className="border border-dashed rounded-2xl p-5"><FileSpreadsheet className="text-teal-700"/><p className="font-semibold mt-2">Plantilla institucional</p><p className="text-xs text-stone-500 mt-1">La primera implementación prioriza una plantilla compatible con Excel para escenarios sin conectividad.</p><button onClick={downloadReferenceTemplate} className="mt-3 border rounded-xl px-3 py-2 text-xs font-semibold flex items-center gap-2"><Download size={14}/> Descargar plantilla</button></div><label className="border border-dashed rounded-2xl p-5 cursor-pointer hover:bg-stone-50"><Upload className="text-violet-600"/><p className="font-semibold mt-2">Cargar plantilla completada</p><p className="text-xs text-stone-500 mt-1">En esta iteración se simula la lectura para validar el flujo.</p><input type="file" accept=".xls,.xlsx,.csv" className="hidden" onChange={e=>simulateExcel(e.target.files?.[0])}/></label></div>:
      <><ProgressSteps steps={steps} current={step}/>{fileName&&<AlertBanner tone="blue" title="Datos precargados desde Excel">{fileName}. Revise la información antes de guardar.</AlertBanner>}
      {step===0&&<div className="grid md:grid-cols-2 gap-4"><div className="md:col-span-2"><PersonSearch people={state.people} role={role} value={form.personId} onSelect={id=>setForm({...form,personId:id})}/></div><Field label="Fecha" required><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className={inputClass}/></Field><Field label="Tipo" required><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className={inputClass}>{REFERENCE_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Origen" required><select value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})} className={inputClass}>{DETECTION_ORIGINS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Responsable de la referencia" hint="Puede diferir del usuario que digita."><input value={form.referredBy} onChange={e=>setForm({...form,referredBy:e.target.value})} className={inputClass}/></Field></div>}
      {step===1&&<div className="space-y-5">{Object.entries(REFERENCE_MOTIVES).map(([group,items])=><div key={group}><p className="text-sm font-bold mb-2">{group}</p><div className="grid md:grid-cols-2 gap-2">{items.map(m=><div key={m} className={`border rounded-xl p-3 ${form.motives.includes(m)?'border-teal-300 bg-teal-50/40':'border-stone-200'}`}><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.motives.includes(m)} onChange={()=>toggleMotive(m)} className="accent-teal-700"/><span>{m}</span></label>{form.motives.includes(m)&&<input value={form.factorDetails[m]||''} onChange={e=>setForm({...form,factorDetails:{...form.factorDetails,[m]:e.target.value}})} className={`${inputClass} mt-2`} placeholder="Especifique o amplíe este factor cuando sea necesario..."/>}</div>)}</div></div>)}</div>}
      {step===2&&<Field label="Información relevante / observaciones" hint="Agregue únicamente el contexto pertinente para el análisis."><textarea rows={6} value={form.observations} onChange={e=>setForm({...form,observations:e.target.value})} className={inputClass}/></Field>}
      {step===3&&<div className="border rounded-2xl p-5 bg-stone-50"><div className="grid md:grid-cols-2 gap-3 text-sm"><p><b>Persona:</b> {selectedPerson?.name||'—'}</p><p><b>Identificación:</b> {selectedPerson?.identification||'—'}</p><p><b>Fecha:</b> {form.date}</p><p><b>Origen:</b> {form.origin}</p><p><b>Tipo:</b> {form.type}</p><p><b>Responsable:</b> {form.referredBy}</p></div><div className="mt-4"><p className="text-xs font-bold uppercase text-stone-500">Motivos y detalle</p><div className="space-y-2 mt-2">{form.motives.map(m=><div key={m} className="bg-white border rounded-xl p-3"><p className="text-sm font-semibold">{m}</p>{form.factorDetails[m]&&<p className="text-xs text-stone-600 mt-1">{form.factorDetails[m]}</p>}</div>)}</div></div><div className="mt-4"><p className="text-xs font-bold uppercase text-stone-500">Información relevante</p><p className="text-sm mt-1">{form.observations||'—'}</p></div></div>}
      <div className="flex justify-between"><button onClick={()=>step===0?reset():setStep(step-1)} className="border rounded-xl px-4 py-2 text-sm font-semibold">{step===0?'Cancelar':'Atrás'}</button>{step<3?<button disabled={step===0&&!form.personId} onClick={()=>setStep(step+1)} className="bg-teal-700 disabled:bg-stone-300 text-white rounded-xl px-4 py-2 text-sm font-semibold">Continuar</button>:<button onClick={submit} className="bg-teal-700 text-white rounded-xl px-4 py-2 text-sm font-semibold">Guardar referencia</button>}</div></>}</div></SectionCard>}
    <div className="grid xl:grid-cols-[1fr_430px] gap-5 items-start"><SectionCard title="Bandeja de referencias" description={`${visible.length} referencia(s) visibles para ${cfg.scope}.`}><div className="space-y-2">{visible.map(r=>{const p=state.people.find(x=>x.id===r.personId);return <button key={r.id} onClick={()=>setSelectedId(r.id)} className={`w-full text-left border rounded-xl p-3 ${selectedId===r.id?'border-teal-300 bg-teal-50/50':'hover:bg-stone-50'}`}><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold">{p?.name}</p><p className="text-xs text-stone-500">{p?.identification} · {r.establishment}</p><p className="text-xs text-stone-400 mt-1">Responsable: {r.referredBy}</p></div><div className="flex flex-col items-end gap-1"><StatusBadge status={r.status}/><Badge tone={r.type==='Urgencia'?'red':'blue'}>{r.type}</Badge></div></div></button>})}</div></SectionCard>
    <SectionCard title="Detalle de referencia">{selected?<div className="space-y-4"><div><p className="text-lg font-bold">{person?.name}</p><p className="text-xs text-stone-500">{person?.identification} · {selected.date}</p></div><div className="flex gap-2"><StatusBadge status={selected.status}/><Badge tone="blue">{selected.origin}</Badge></div><div><p className="text-xs font-bold uppercase text-stone-400">Motivos</p><div className="space-y-2 mt-2">{selected.motives.map(m=><div key={m} className="border rounded-xl p-3"><p className="text-sm font-semibold">{m}</p>{selected.factorDetails?.[m]&&<p className="text-xs mt-1 text-stone-600">{selected.factorDetails[m]}</p>}</div>)}</div></div><div><p className="text-xs font-bold uppercase text-stone-400">Información relevante</p><p className="text-sm mt-1">{selected.observations}</p></div><div><p className="text-xs text-stone-500">Responsable: <b>{selected.referredBy}</b></p></div><button onClick={()=>printReference(selected,person)} className="w-full border rounded-xl py-2.5 text-sm font-semibold flex items-center justify-center gap-2"><Printer size={15}/> Imprimir referencia</button>{cfg.level==='local'&&['Recibida','Pendiente de revisión'].includes(selected.status)&&<button onClick={()=>actions.updateReference(selected.id,{status:'Recibida'})} className="w-full bg-teal-700 text-white rounded-xl py-2.5 text-sm font-semibold">Marcar recibida</button>}</div>:<p className="text-sm text-stone-500">Seleccione una referencia.</p>}</SectionCard></div>
  </div>;
}
