import React,{useMemo,useState} from 'react';
import { BarChart3, Download, Users } from 'lucide-react';
import { Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { HELP_TEXT, PRIORITIES } from '../data/catalogs';
import { applyHierarchyFilters, roleConfig, roleFilters, scopeItems, unique } from '../utils/access';
import { downloadExcelLike } from '../utils/download';
import { Badge, HelpStrip, MetricCard, PageHeader, SectionCard, inputClass } from '../components/ui';

export default function ReportingPage({state,role}){
  const cfg=roleConfig(role); const options=roleFilters(role,state.people); const [filters,setFilters]=useState({year:'2026',region:'',localOffice:'',establishment:'',status:'',priority:'',discipline:'',professional:''});
  const casesBase=scopeItems(state.cases,role); const refsBase=scopeItems(state.references,role);
  const cases=useMemo(()=>applyHierarchyFilters(casesBase,filters).filter(c=>(!filters.status||c.status===filters.status)&&(!filters.priority||c.priority===filters.priority)&&String(c.openedAt||'').startsWith(filters.year)),[casesBase,filters]);
  const refs=useMemo(()=>applyHierarchyFilters(refsBase,filters).filter(r=>String(r.date||'').startsWith(filters.year)),[refsBase,filters]);
  const events=useMemo(()=>state.timeline.filter(e=>{const c=cases.find(x=>x.id===e.caseId);if(!c)return false;if(['Sesión interdisciplinaria','Cierre','Traslado'].includes(e.type))return false;if(filters.discipline&&e.discipline!==filters.discipline)return false;if(filters.professional&&e.professional!==filters.professional)return false;return String(e.date||'').startsWith(filters.year)}),[state.timeline,cases,filters]);
  const uniquePeople=new Set(events.map(e=>cases.find(c=>c.id===e.caseId)?.personId).filter(Boolean)).size;
  const priorityData=PRIORITIES.map(p=>({name:p,value:cases.filter(c=>c.priority===p).length}));
  const stateData=unique(cases.map(c=>c.status)).map(s=>({name:s,value:cases.filter(c=>c.status===s).length}));
  const disciplines=unique(events.map(e=>e.discipline)); const disciplineData=disciplines.map(d=>{const ev=events.filter(e=>e.discipline===d);const persons=new Set(ev.map(e=>cases.find(c=>c.id===e.caseId)?.personId).filter(Boolean));return{name:d,Atenciones:ev.length,Personas:persons.size}});
  const professionals=unique(state.timeline.map(e=>e.professional));
  const exportConsolidado=()=>downloadExcelLike(`consolidado_${filters.year}`,[ 'Indicador','Valor' ],[['Casos',cases.length],['Referencias',refs.length],['Personas únicas atendidas',uniquePeople],['Atenciones',events.length],...priorityData.map(x=>[`Prioridad ${x.name}`,x.value])]);
  return <div className="space-y-6"><PageHeader eyebrow="Analítica operativa" title="Reportería" description="Aplique primero los filtros. Las métricas, visualizaciones y el consolidado responden al mismo corte." actions={<button onClick={exportConsolidado} className="border px-3 py-2 rounded-xl text-sm font-semibold flex gap-2 items-center"><Download size={15}/> Descargar consolidado</button>}/><HelpStrip>{HELP_TEXT.reporting}</HelpStrip>
    <SectionCard title="Filtros"><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3"><select value={filters.year} onChange={e=>setFilters({...filters,year:e.target.value})} className={inputClass}><option>2026</option><option>2025</option><option>2024</option></select>{options.regions.length>0&&<select value={filters.region} onChange={e=>setFilters({...filters,region:e.target.value,localOffice:'',establishment:''})} className={inputClass}><option value="">Todas las regiones</option>{options.regions.map(x=><option key={x}>{x}</option>)}</select>}{options.localOffices.length>0&&<select value={filters.localOffice} onChange={e=>setFilters({...filters,localOffice:e.target.value,establishment:''})} className={inputClass}><option value="">Todas las OL</option>{options.localOffices.map(x=><option key={x}>{x}</option>)}</select>}{options.establishments.length>0&&<select value={filters.establishment} onChange={e=>setFilters({...filters,establishment:e.target.value})} className={inputClass}><option value="">Todos los establecimientos</option>{options.establishments.map(x=><option key={x}>{x}</option>)}</select>}<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className={inputClass}><option value="">Todos los estados</option>{unique(casesBase.map(c=>c.status)).map(x=><option key={x}>{x}</option>)}</select><select value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})} className={inputClass}><option value="">Todas las prioridades</option>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select><select value={filters.discipline} onChange={e=>setFilters({...filters,discipline:e.target.value})} className={inputClass}><option value="">Todas las disciplinas</option>{unique(state.timeline.map(e=>e.discipline)).map(x=><option key={x}>{x}</option>)}</select><select value={filters.professional} onChange={e=>setFilters({...filters,professional:e.target.value})} className={inputClass}><option value="">Todos los profesionales</option>{professionals.map(x=><option key={x}>{x}</option>)}</select></div></SectionCard>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><MetricCard label="Casos del corte" value={cases.length} icon={BarChart3} tone="teal"/><MetricCard label="Referencias" value={refs.length} icon={BarChart3} tone="amber"/><MetricCard label="Personas únicas atendidas" value={uniquePeople} icon={Users} tone="blue" helper="No equivale a cantidad de atenciones"/><MetricCard label="Total de atenciones" value={events.length} icon={Users} tone="purple" helper="Una persona puede tener varias"/></div>
    <div className="grid xl:grid-cols-2 gap-5"><ChartCard title="Casos por prioridad" data={priorityData}/><ChartCard title="Casos por estado" data={stateData}/></div>
    <SectionCard title="Personas atendidas vs total de atenciones" description="Estas dos métricas se muestran por separado para representar mejor la carga de trabajo."><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={disciplineData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="Personas" fill="#0f766e" radius={[5,5,0,0]}/><Bar dataKey="Atenciones" fill="#7c3aed" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></SectionCard>
    <SectionCard title="Consolidado dinámico" description="No requiere remisión interna a Nacional: el ámbito superior puede consultar y descargar la misma información según permisos."><div className="grid md:grid-cols-4 gap-3"><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Año</p><p className="font-bold mt-1">{filters.year}</p></div><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Ámbito</p><p className="font-bold mt-1">{filters.establishment||filters.localOffice||filters.region||cfg.scope}</p></div><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Casos</p><p className="font-bold mt-1">{cases.length}</p></div><div className="border rounded-xl p-3"><p className="text-xs text-stone-400">Atenciones</p><p className="font-bold mt-1">{events.length}</p></div></div></SectionCard>
  </div>;
}

function ChartCard({title,data}){return <SectionCard title={title}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#0f766e" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></SectionCard>}
