import React,{useMemo,useState} from 'react';
import { CalendarDays, Plus } from 'lucide-react';
import { HELP_TEXT, SCHEDULE_STATUSES, SCHEDULE_TYPES } from '../data/catalogs';
import { canEditOperational, roleConfig, roleFilters, scopeItems, applyHierarchyFilters } from '../utils/access';
import { AlertBanner, Badge, Field, HelpStrip, PageHeader, SectionCard, StatusBadge, inputClass } from '../components/ui';

export default function SchedulePage({state,actions,role}){
  const editable=canEditOperational(role); const cfg=roleConfig(role); const options=roleFilters(role,state.people); const base=scopeItems(state.schedule,role);
  const [filters,setFilters]=useState({region:'',localOffice:'',establishment:'',status:''}); const [creating,setCreating]=useState(false); const [editingId,setEditingId]=useState(null);
  const [form,setForm]=useState({date:'2026-09-24',type:'Sesión interdisciplinaria',title:'',localOffice:cfg.level==='local'?cfg.scope:'Oficina Local Alajuela',establishment:'',region:'Región Central Norte',status:'Programada',reason:'',notes:''});
  const filtered=useMemo(()=>applyHierarchyFilters(base,filters).filter(x=>!filters.status||x.status===filters.status).sort((a,b)=>a.date.localeCompare(b.date)),[base,filters]);
  const overdue=filtered.filter(x=>x.status==='Programada'&&x.date<'2026-09-16');
  const save=()=>{actions.addSchedule(form);setCreating(false);setForm({...form,title:'',reason:'',notes:''})};
  const updateStatus=(id,status)=>setEditingId(id===editingId?null:id);
  return <div className="space-y-6"><PageHeader eyebrow="Planificación operativa" title="Programación" description="Oficina Local programa sesiones y atenciones. Regional y Nacional consultan la programación de su ámbito sin modificarla." actions={editable&&<button onClick={()=>setCreating(!creating)} className="bg-teal-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold flex gap-2 items-center"><Plus size={16}/> Programar actividad</button>}/><HelpStrip>{HELP_TEXT.schedule}</HelpStrip>
    {overdue.length>0&&editable&&<AlertBanner tone="amber" title="Actividades con fecha vencida">{overdue.length} actividad(es) siguen como Programada. Actualice si fueron realizadas, reprogramadas o canceladas.</AlertBanner>}
    {creating&&<SectionCard title="Nueva actividad programada"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Fecha"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className={inputClass}/></Field><Field label="Tipo"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className={inputClass}>{SCHEDULE_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Título / propósito"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={inputClass}/></Field><Field label="Establecimiento" hint="Opcional para sesiones generales"><input value={form.establishment} onChange={e=>setForm({...form,establishment:e.target.value})} className={inputClass}/></Field><div className="lg:col-span-2"><Field label="Observaciones"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className={inputClass}/></Field></div></div><button disabled={!form.title} onClick={save} className="mt-4 bg-teal-700 disabled:bg-stone-300 text-white px-4 py-2 rounded-xl text-sm font-semibold">Guardar programación</button></SectionCard>}
    <SectionCard title="Filtros"><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3">{options.regions.length>0&&<select value={filters.region} onChange={e=>setFilters({...filters,region:e.target.value,localOffice:'',establishment:''})} className={inputClass}><option value="">Todas las regiones</option>{options.regions.map(x=><option key={x}>{x}</option>)}</select>}{options.localOffices.length>0&&<select value={filters.localOffice} onChange={e=>setFilters({...filters,localOffice:e.target.value,establishment:''})} className={inputClass}><option value="">Todas las OL</option>{options.localOffices.map(x=><option key={x}>{x}</option>)}</select>}{options.establishments.length>0&&<select value={filters.establishment} onChange={e=>setFilters({...filters,establishment:e.target.value})} className={inputClass}><option value="">Todos los establecimientos</option>{options.establishments.map(x=><option key={x}>{x}</option>)}</select>}<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className={inputClass}><option value="">Todos los estados</option>{SCHEDULE_STATUSES.map(x=><option key={x}>{x}</option>)}</select></div></SectionCard>
    <SectionCard title="Listado cronológico" description={`${filtered.length} actividad(es). Vista principal en lista para facilitar revisión anual.`}><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-stone-500 border-b"><th className="py-2 pr-3">Fecha</th><th className="py-2 pr-3">Actividad</th><th className="py-2 pr-3">Ámbito</th><th className="py-2 pr-3">Estado</th>{editable&&<th className="py-2">Acción</th>}</tr></thead><tbody>{filtered.map(item=><React.Fragment key={item.id}><tr className="border-b border-stone-100"><td className="py-3 pr-3 whitespace-nowrap">{item.date}</td><td className="py-3 pr-3"><p className="font-semibold">{item.title}</p><p className="text-xs text-stone-500">{item.type}</p></td><td className="py-3 pr-3"><p>{item.localOffice}</p><p className="text-xs text-stone-500">{item.establishment||'Actividad de OL'}</p></td><td className="py-3 pr-3"><StatusBadge status={item.status}/>{item.reason&&<p className="text-xs text-stone-500 mt-1">{item.reason}</p>}</td>{editable&&<td className="py-3"><button onClick={()=>setEditingId(editingId===item.id?null:item.id)} className="border rounded-lg px-2.5 py-1.5 text-xs font-semibold">Actualizar</button></td>}</tr>{editable&&editingId===item.id&&<tr><td colSpan="5" className="bg-stone-50 p-3"><ScheduleUpdate item={item} onSave={(patch)=>{actions.updateSchedule(item.id,patch);setEditingId(null)}}/></td></tr>}</React.Fragment>)}</tbody></table></div></SectionCard>
  </div>;
}

function ScheduleUpdate({item,onSave}){const [status,setStatus]=useState(item.status);const [reason,setReason]=useState('');const [newDate,setNewDate]=useState(item.date);const needsReason=['Reprogramada','Cancelada'].includes(status);return <div className="grid md:grid-cols-4 gap-3 items-end"><Field label="Nuevo estado"><select value={status} onChange={e=>setStatus(e.target.value)} className={inputClass}>{SCHEDULE_STATUSES.map(x=><option key={x}>{x}</option>)}</select></Field>{status==='Reprogramada'&&<Field label="Nueva fecha" required><input type="date" value={newDate} onChange={e=>setNewDate(e.target.value)} className={inputClass}/></Field>}{needsReason&&<Field label="Motivo" required><input value={reason} onChange={e=>setReason(e.target.value)} className={inputClass}/></Field>}<button disabled={needsReason&&!reason} onClick={()=>onSave({status,date:status==='Reprogramada'?newDate:item.date,reason})} className="bg-stone-900 disabled:bg-stone-300 text-white rounded-xl px-3 py-2 text-sm font-semibold">Guardar cambio</button></div>}
