import React,{useMemo,useState} from 'react';
import { Plus, Search } from 'lucide-react';
import { DISCIPLINES, HELP_TEXT, PRIORITIES, RISK_MATRIX, STRATEGIES } from '../data/catalogs';
import { scopeItems } from '../utils/access';
import { Badge, Field, HelpStrip, PageHeader, SectionCard, StatusBadge, inputClass } from '../components/ui';

const frequencyOptions=['Semanal','Quincenal','Mensual','Bimensual','Según necesidad'];

export default function SessionsPage({state,actions,role,onNavigate}){
  const refs=scopeItems(state.references,role).filter(r=>['Recibida','Pendiente de revisión'].includes(r.status));
  const [selectedSessionId,setSelectedSessionId]=useState(state.sessions[0]?.id);
  const [selectedRefId,setSelectedRefId]=useState(state.sessions[0]?.referenceIds?.[0]||refs[0]?.id);
  const [query,setQuery]=useState('');
  const [newOpen,setNewOpen]=useState(false);
  const [sessionForm,setSessionForm]=useState({date:'2026-09-20',place:'Oficina Local Alajuela',startTime:'09:00',endTime:'11:00',participants:['Psicología','Nutrición'],referenceIds:[]});
  const [valuation,setValuation]=useState({selected:{},details:{},decision:'',priority:'Moderado',strategies:[],disciplines:[],frequency:'Mensual',summary:''});
  const session=state.sessions.find(s=>s.id===selectedSessionId)||state.sessions[0];
  const currentRef=state.references.find(r=>r.id===selectedRefId);
  const person=state.people.find(p=>p.id===currentRef?.personId);
  const searchResults=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return [];return refs.filter(r=>{const p=state.people.find(x=>x.id===r.personId);return p?.name.toLowerCase().includes(q)||p?.identification.toLowerCase().includes(q)}).slice(0,8)},[query,refs,state.people]);
  const toggle=(key)=>setValuation(v=>{const selected={...v.selected,[key]:!v.selected[key]};const details={...v.details};if(!selected[key])delete details[key];return{...v,selected,details}});
  const createCase=()=>{if(!currentRef||valuation.decision!=='Sí')return;actions.createCaseFromReference(currentRef.id,{openedAt:'2026-09-16',priority:valuation.priority,purposes:valuation.summary?[valuation.summary]:[],strategies:valuation.strategies,disciplines:valuation.disciplines,frequency:valuation.frequency,valuationSummary:valuation.summary});actions.updateSession(session.id,{referenceIds:session.referenceIds.filter(id=>id!==currentRef.id)});onNavigate('cases')};
  const addToSession=(id)=>{if(!session)return;const ids=[...new Set([...(session.referenceIds||[]),id])];actions.updateSession(session.id,{referenceIds:ids});setSelectedRefId(id);setQuery('')};
  return <div className="space-y-6"><PageHeader eyebrow="Equipo Interdisciplinario" title="Sesiones interdisciplinarias" description="Una sesión puede analizar múltiples casos. Cada persona conserva su valoración, resolución y abordaje." actions={<button onClick={()=>setNewOpen(!newOpen)} className="bg-teal-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold flex gap-2 items-center"><Plus size={16}/> Nueva sesión</button>}/><HelpStrip>{HELP_TEXT.sessions}</HelpStrip>
  {newOpen&&<SectionCard title="Crear sesión"><div className="grid md:grid-cols-4 gap-3"><Field label="Fecha"><input type="date" value={sessionForm.date} onChange={e=>setSessionForm({...sessionForm,date:e.target.value})} className={inputClass}/></Field><Field label="Inicio"><input type="time" value={sessionForm.startTime} onChange={e=>setSessionForm({...sessionForm,startTime:e.target.value})} className={inputClass}/></Field><Field label="Fin"><input type="time" value={sessionForm.endTime} onChange={e=>setSessionForm({...sessionForm,endTime:e.target.value})} className={inputClass}/></Field><Field label="Lugar"><input value={sessionForm.place} onChange={e=>setSessionForm({...sessionForm,place:e.target.value})} className={inputClass}/></Field></div><div className="mt-4"><p className="text-xs font-semibold mb-2">Disciplinas participantes</p><div className="flex flex-wrap gap-2">{DISCIPLINES.map(d=><button key={d} onClick={()=>setSessionForm(f=>({...f,participants:f.participants.includes(d)?f.participants.filter(x=>x!==d):[...f.participants,d]}))} className={`px-3 py-1.5 rounded-full border text-xs ${sessionForm.participants.includes(d)?'bg-teal-50 border-teal-300 text-teal-800':''}`}>{d}</button>)}</div></div><button onClick={()=>{actions.addSession({...sessionForm,status:'Programada',agreements:[]});setNewOpen(false)}} className="mt-4 bg-teal-700 text-white px-4 py-2 rounded-xl text-sm font-semibold">Guardar sesión</button></SectionCard>}
  <div className="grid xl:grid-cols-[320px_1fr] gap-5 items-start"><SectionCard title="Sesiones"><div className="space-y-2">{state.sessions.map(s=><button key={s.id} onClick={()=>{setSelectedSessionId(s.id);setSelectedRefId(s.referenceIds?.[0]||null)}} className={`w-full text-left border rounded-xl p-3 ${s.id===selectedSessionId?'border-violet-300 bg-violet-50/50':''}`}><div className="flex justify-between"><div><p className="text-sm font-semibold">{s.date}</p><p className="text-xs text-stone-500">{s.place} · {s.referenceIds.length} caso(s)</p></div><StatusBadge status={s.status}/></div></button>)}</div></SectionCard>
  {session&&<div className="space-y-5"><SectionCard title={`Sesión ${session.date}`} description="Busque referencias/casos; no se muestran listas masivas."><div className="relative"><Search size={15} className="absolute left-3 top-3 text-stone-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className={`${inputClass} pl-9`} placeholder="Buscar por identificación o nombre"/>{query&&<div className="absolute z-20 bg-white border rounded-xl shadow-lg mt-1 w-full">{searchResults.map(r=>{const p=state.people.find(x=>x.id===r.personId);return <button key={r.id} onClick={()=>addToSession(r.id)} className="w-full text-left p-3 hover:bg-stone-50"><p className="text-sm font-semibold">{p?.name}</p><p className="text-xs text-stone-500">{p?.identification} · {r.establishment}</p></button>})}</div>}</div><div className="flex gap-2 flex-wrap mt-4">{session.referenceIds.map(id=>{const r=state.references.find(x=>x.id===id),p=state.people.find(x=>x.id===r?.personId);return <button key={id} onClick={()=>setSelectedRefId(id)} className={`px-3 py-2 rounded-xl border text-sm ${selectedRefId===id?'border-teal-300 bg-teal-50':''}`}>{p?.name||id}</button>})}</div></SectionCard>
  {currentRef&&<SectionCard title={`Valoración — ${person?.name}`} description="Registre factores por ámbito. La intensidad/frecuencia/persistencia no se exige en esta iteración."><div className="space-y-6">{Object.entries(RISK_MATRIX).map(([area,groups])=><div key={area}><h4 className="font-bold text-sm mb-3">{area}</h4><div className="grid lg:grid-cols-3 gap-3">{[['protectores','Factores protectores'],['riesgos','Factores de riesgo'],['alertas','Signos de alerta']].map(([g,label])=><div key={g} className="border rounded-xl p-3"><p className="text-xs font-bold text-stone-500 uppercase">{label}</p><div className="space-y-2 mt-3">{groups[g].map(item=>{const key=`${area}|${g}|${item}`;return <div key={key} className={`rounded-xl border p-2.5 ${valuation.selected[key]?'border-teal-300 bg-teal-50/40':''}`}><label className="flex gap-2 text-xs"><input type="checkbox" checked={!!valuation.selected[key]} onChange={()=>toggle(key)} className="accent-teal-700"/><span>{item}</span></label>{valuation.selected[key]&&<input value={valuation.details[key]||''} onChange={e=>setValuation(v=>({...v,details:{...v.details,[key]:e.target.value}}))} className={`${inputClass} mt-2 text-xs`} placeholder="Especifique este factor si es necesario..."/>}</div>})}</div></div>)}</div></div>)}
  <div className="border-t pt-5"><Field label="¿Requiere Atención Interdisciplinaria?"><div className="flex gap-2 mt-1">{['Sí','No'].map(x=><button key={x} onClick={()=>setValuation({...valuation,decision:x})} className={`px-4 py-2 rounded-xl border text-sm font-semibold ${valuation.decision===x?'bg-teal-700 text-white border-teal-700':''}`}>{x}</button>)}</div></Field></div>
  {valuation.decision==='Sí'&&<div className="grid md:grid-cols-2 gap-4"><Field label="Prioridad"><select value={valuation.priority} onChange={e=>setValuation({...valuation,priority:e.target.value})} className={inputClass}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Frecuencia"><select value={valuation.frequency} onChange={e=>setValuation({...valuation,frequency:e.target.value})} className={inputClass}>{frequencyOptions.map(x=><option key={x}>{x}</option>)}</select></Field><div><p className="text-xs font-semibold mb-2">Estrategias</p><div className="flex flex-wrap gap-2">{STRATEGIES.map(x=><button key={x} onClick={()=>setValuation(v=>({...v,strategies:v.strategies.includes(x)?v.strategies.filter(a=>a!==x):[...v.strategies,x]}))} className={`px-2.5 py-1.5 rounded-full border text-xs ${valuation.strategies.includes(x)?'bg-teal-50 border-teal-300':''}`}>{x}</button>)}</div></div><div><p className="text-xs font-semibold mb-2">Disciplinas</p><div className="flex flex-wrap gap-2">{DISCIPLINES.map(x=><button key={x} onClick={()=>setValuation(v=>({...v,disciplines:v.disciplines.includes(x)?v.disciplines.filter(a=>a!==x):[...v.disciplines,x]}))} className={`px-2.5 py-1.5 rounded-full border text-xs ${valuation.disciplines.includes(x)?'bg-violet-50 border-violet-300':''}`}>{x}</button>)}</div></div><div className="md:col-span-2"><Field label="Resumen / propósito"><textarea rows={3} value={valuation.summary} onChange={e=>setValuation({...valuation,summary:e.target.value})} className={inputClass}/></Field></div></div>}
  <div className="flex justify-end">{valuation.decision==='Sí'?<button onClick={createCase} className="bg-teal-700 text-white px-4 py-2.5 rounded-xl text-sm font-semibold">Confirmar y abrir caso A.I.</button>:valuation.decision==='No'?<button onClick={()=>actions.updateReference(currentRef.id,{status:'No requiere A.I.'})} className="bg-stone-800 text-white px-4 py-2.5 rounded-xl text-sm font-semibold">Registrar que no requiere A.I.</button>:<Badge tone="amber">Pendiente de decisión</Badge>}</div></div></SectionCard>}</div>}</div></div>;
}
